### ISSUE TITLE
Examples' source code

### ISSUE THREAD

**Issue by blurdylan** [Aminerman/vue-kinesis#23]
Most of the examples on the website look cool!
However, the little snippets showed are not explicit enough to comprehend what was done to achieve that. It'll be great to have their source.

**Comment by Aminerman** [comment]
Hello, 
Thank you for your feedback and I totally understand your point. It was a choice to make it this way because the code snippets would have been unnecessarily long and cluttered (especially for SVG) so I wanted to focus on the principles behind each example.

I'm planning to add another page that will detail each property and how it can be used. I guess it will be more helpful. But I'll also think of a way to make the snippets more explicit without having to replicate all the unnecessary code.

In the meanwhile, if you want specifi help with what you're trying to achieve you can contact me on Twitter or DM me on Instagram and I'll try to help as much as I can.

**Comment by zipme** [comment]
Great library @Aminerman , I am also looking for the source code of the examples, would be very helpful in understanding the  usage, especially the svg example. Thanks!

**Comment by Gredys** [comment]
One year later. No examples. Nice.

**Comment by Aminerman** [comment]
@Gredys 
Sorry that my life wasn't very easy this year and didn't completely revolve around this project :)

**Comment by bdiouih** [comment]
@Aminerman 

You have an excellent library there, but the lack of examples' code lead to the developers not using the library.
This is also our case. It's a pity.

**Comment by Aminerman** [comment]
@bdiouih 
I understand. I'm almost done rewriting a more comprehensive doc that will be shipped with a new version and new features.
Meanwhile, these links might help you: 
https://blog.logrocket.com/interactive-vue-animations-with-kinesis/
https://blog.logrocket.com/top-5-vue-animation-libraries-compared/

**Comment by Aminerman** [comment]
@bdiouih 
I added some more to the README

**Comment by bdiouih** [comment]
Thank you very much @Aminerman 
we are looking more at the examples
