### ISSUE TITLE
Not working in NuxtJS

### ISSUE THREAD

**Issue by zernonia** [Aminerman/vue-kinesis#27]
I've tried to implement this onto my NuxtJS apps, but it doesn't show any animation. I've checked the DOM and it seems everything render nicely.

Perhaps something config problem? or my coding for <kinesis-container> and <kinesis-element> has some issue. Would love to see the code for demo on the websites too

`<kinesis-container event="scroll" >
      <kinesis-element strength="100">
        <div class="init"><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span><span></span></div>
      </div>
       </kinesis-element>
</kinesis-container>`

**Comment by Aminerman** [comment]
Do you have any errors showing up in the console? 
In the code you sent you have an extra `</div>`. Could it be the problem?
If none of the above, would it be possible for you to send me a small nuxt project that has only this code snippet so I can debug it?

**Comment by Aminerman** [comment]
Maybe you'd want to take a look at this tutorial by @leonardogruppelli :
https://medium.com/@leonardo.gruppelli/kinesis-awesome-animations-for-your-vue-nuxt-applications-8c16ae701e92

Maybe this might help: 

`A VERY IMPORTANT NOTE: if you're using Nuxt on Universal Mode and want to use the <kinesis-container /> with the scroll event, you'll need to wrap the <kinesis-container /> with a <client-only> tag, because the <kinesis-container event="scroll" /> depends on navigator properties, which are only available on the browser. `

**Comment by Aminerman** [comment]
I'll close the issue for now. You can reopen it if this doesn't fix your problem.
